// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3p4RMMWS88k_XpefoOqY7bWYna358Rzg',
    appId: '1:645324287222:web:cf6a2c9dbea970712590d7',
    messagingSenderId: '645324287222',
    projectId: 'loops-d84ba',
    authDomain: 'loops-d84ba.firebaseapp.com',
    storageBucket: 'loops-d84ba.appspot.com',
    measurementId: 'G-271VXH44V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhppNBXALj4TxV3nlXdH6QoBVeAv6vGGU',
    appId: '1:645324287222:android:db5f899064b4489b2590d7',
    messagingSenderId: '645324287222',
    projectId: 'loops-d84ba',
    storageBucket: 'loops-d84ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQyz09Msdxa0PADNDcb0W5zqJunTq5jo',
    appId: '1:645324287222:ios:1510c8e4fd69233b2590d7',
    messagingSenderId: '645324287222',
    projectId: 'loops-d84ba',
    storageBucket: 'loops-d84ba.appspot.com',
    iosClientId: '645324287222-1d3007du81kdaedms2h9kt5lvkt5krl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.odds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRQyz09Msdxa0PADNDcb0W5zqJunTq5jo',
    appId: '1:645324287222:ios:8aa344d8b6e050e82590d7',
    messagingSenderId: '645324287222',
    projectId: 'loops-d84ba',
    storageBucket: 'loops-d84ba.appspot.com',
    iosClientId: '645324287222-91aqrr4ts6ar5hio440e5rlmhb4ndddn.apps.googleusercontent.com',
    iosBundleId: 'com.example.odds3',
  );
}
